-- +goose Up
ALTER TABLE auth.users ADD COLUMN IF NOT EXISTS rating_sum BIGINT NOT NULL DEFAULT 0;
ALTER TABLE auth.users ADD COLUMN IF NOT EXISTS rating_count INTEGER NOT NULL DEFAULT 0;
ALTER TABLE auth.users ADD COLUMN IF NOT EXISTS rating_avg NUMERIC(3,2) NOT NULL DEFAULT 0.00;

-- +goose Down
ALTER TABLE auth.users DROP COLUMN IF EXISTS rating_avg;
ALTER TABLE auth.users DROP COLUMN IF EXISTS rating_count;
ALTER TABLE auth.users DROP COLUMN IF EXISTS rating_sum;