-- +goose Up
-- +goose NO TRANSACTION

CREATE TYPE long_distance_type AS ENUM ('ONE_WAY', 'RETURN', 'MULTI_DAY');

ALTER TYPE trip_status ADD VALUE IF NOT EXISTS 'SEARCHING_DRIVERS';
ALTER TYPE trip_status ADD VALUE IF NOT EXISTS 'DRIVER_SELECTED';
ALTER TYPE trip_status ADD VALUE IF NOT EXISTS 'QUOTE_GENERATED';
ALTER TYPE trip_status ADD VALUE IF NOT EXISTS 'DRIVER_CONFIRMED';
ALTER TYPE trip_status ADD VALUE IF NOT EXISTS 'SCHEDULED';
ALTER TYPE trip_status ADD VALUE IF NOT EXISTS 'OUTBOUND_IN_PROGRESS';
ALTER TYPE trip_status ADD VALUE IF NOT EXISTS 'DESTINATION_REACHED';
ALTER TYPE trip_status ADD VALUE IF NOT EXISTS 'DRIVER_RETAINED';
ALTER TYPE trip_status ADD VALUE IF NOT EXISTS 'RETURN_SCHEDULED';
ALTER TYPE trip_status ADD VALUE IF NOT EXISTS 'RETURN_STARTED';
ALTER TYPE trip_status ADD VALUE IF NOT EXISTS 'RETURN_IN_PROGRESS';
ALTER TYPE trip_status ADD VALUE IF NOT EXISTS 'FINAL_DESTINATION';

ALTER TABLE trips ADD COLUMN long_distance_type long_distance_type;
ALTER TABLE trips ADD COLUMN scheduled_departure TIMESTAMPTZ;
ALTER TABLE trips ADD COLUMN scheduled_return TIMESTAMPTZ;
ALTER TABLE trips ADD COLUMN trip_duration_days INTEGER;

-- +goose Down
ALTER TABLE trips DROP COLUMN IF EXISTS trip_duration_days;
ALTER TABLE trips DROP COLUMN IF EXISTS scheduled_return;
ALTER TABLE trips DROP COLUMN IF EXISTS scheduled_departure;
ALTER TABLE trips DROP COLUMN IF EXISTS long_distance_type;
DROP TYPE IF EXISTS long_distance_type;