basePath: /api/v1
host: localhost:8080
info:
  contact:
    email: support@vaya.co.za
    name: API Support
    url: http://www.vaya.co.za/support
  description: This is a complete, production-ready e-hailing backend API.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Vaya E-Hailing API
  version: "1.0"
paths: {}
securityDefinitions:
  BasicAuth:
    type: basic
  BearerAuth:
    description: 'Enter your Bearer token in the format: Bearer {token}'
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
